# -*- coding: utf-8 -*-
"""Olá, este é o Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

####EXERCICIO 1
"""

def filtrar_pares(numeros):
    pares = []
    for numero in numeros:
        if numero % 2 ==0:
            pares.append(numero)
    return pares

lista_inteiros = [1, 3, 5, 6, 8, 12, 2, 4]
resultado = filtrar_pares(lista_inteiros)
print(resultado)

"""####EXERCICIO 2"""

def conta_str(palavra):
    contagem = {}
    for caractere in palavra:
        if caractere in contagem:
            contagem[caractere] += 1
        else:
            contagem[caractere] = 1
    return contagem

texto = "laranja"
resultado = conta_str(texto)
print (resultado)

"""####EXERCICIO 3"""

