# -*- coding: utf-8 -*-
"""Olá, este é o Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

class produto:
  def __init__(self, nome, preco):
    self.nome = nome
    self.preco = preco

class carrinho:
  def __init__(self):
    self.lista_produtos = []

  def add_produto(self, produto):
    self.lista_produtos.append(produto)

  def remover_produto(self, produto):
    self.lista_produtos.remove(produto)

  def calcular_total(self):
    total = 0
    for p in self.lista_produtos:
      total += p.preco
    return total

p1 = produto("ar condicionado", 2499.00)
p2 = produto("Lava e Seca (Samsung)", 3499.00)
p3 = produto("Microondas", 450.00)
p4 = produto("PS5", 3999.90)

carrinho_site = carrinho()
carrinho_site.add_produto(p1)
carrinho_site.add_produto(p2)
carrinho_site.add_produto(p3)
carrinho_site.add_produto(p4)

print("Total da compra: R$",
  carrinho_site.calcular_total())